In [1]:
import polars as pl
import polars.selectors as cs

import altair as alt
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df_path = '/Users/zygimantas/Documents/DataSets/Dataset salary 2024.csv'

In [3]:
df = pl.read_csv(df_path)

In [4]:
df

shape: (16_534, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ work_year ┆ experienc ┆ employmen ┆ job_title ┆ … ┆ employee_ ┆ remote_ra ┆ company_l ┆ company_ │
│ ---       ┆ e_level   ┆ t_type    ┆ ---       ┆   ┆ residence ┆ tio       ┆ ocation   ┆ size     │
│ i64       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆           ┆   ┆ str       ┆ i64       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2024      ┆ SE        ┆ FT        ┆ AI        ┆ … ┆ US        ┆ 0         ┆ US        ┆ M        │
│           ┆           ┆           ┆ Engineer  ┆   ┆           ┆           ┆           ┆          │
│ 2024      ┆ SE        ┆ FT        ┆ AI        ┆ … ┆ US        ┆ 0         ┆ US        ┆ M        │
│           ┆           ┆           ┆ Engineer  ┆   ┆           ┆           ┆           ┆          │
│ 2024      ┆ SE        ┆ FT        ┆ Data      ┆ … ┆ US        ┆ 0         ┆ US        ┆ M        │
│           ┆           ┆           ┆ Engineer  ┆   ┆           ┆           ┆           ┆          │
│ 2024      ┆ SE        ┆ FT        ┆ Data      ┆ … ┆ US        ┆ 0         ┆ US        ┆ M        │
│           ┆           ┆           ┆ Engineer  ┆   ┆           ┆           ┆           ┆          │
│ 2024      ┆ SE        ┆ FT        ┆ Machine   ┆ … ┆ US        ┆ 0         ┆ US        ┆ M        │
│           ┆           ┆           ┆ Learning  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Engineer  ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2020      ┆ SE        ┆ FT        ┆ Data      ┆ … ┆ US        ┆ 100       ┆ US        ┆ L        │
│           ┆           ┆           ┆ Scientist ┆   ┆           ┆           ┆           ┆          │
│ 2021      ┆ MI        ┆ FT        ┆ Principal ┆ … ┆ US        ┆ 100       ┆ US        ┆ L        │
│           ┆           ┆           ┆ Data      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Scientist ┆   ┆           ┆           ┆           ┆          │
│ 2020      ┆ EN        ┆ FT        ┆ Data      ┆ … ┆ US        ┆ 100       ┆ US        ┆ S        │
│           ┆           ┆           ┆ Scientist ┆   ┆           ┆           ┆           ┆          │
│ 2020      ┆ EN        ┆ CT        ┆ Business  ┆ … ┆ US        ┆ 100       ┆ US        ┆ L        │
│           ┆           ┆           ┆ Data      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Analyst   ┆   ┆           ┆           ┆           ┆          │
│ 2021      ┆ SE        ┆ FT        ┆ Data      ┆ … ┆ IN        ┆ 50        ┆ IN        ┆ L        │
│           ┆           ┆           ┆ Science   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Manager   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
df.group_by(
    pl.col('job_title')
).agg(
    pl.sum('salary').alias('total_salary'),
    pl.mean('salary').alias('avg_salary'),
    pl.len().alias('count'),
).sort(
    'avg_salary', descending=False
).filter(
    pl.col('count') > 10
)

shape: (70, 4)
┌─────────────────────────────────┬──────────────┬───────────────┬───────┐
│ job_title                       ┆ total_salary ┆ avg_salary    ┆ count │
│ ---                             ┆ ---          ┆ ---           ┆ ---   │
│ str                             ┆ i64          ┆ f64           ┆ u32   │
╞═════════════════════════════════╪══════════════╪═══════════════╪═══════╡
│ Insight Analyst                 ┆ 596000       ┆ 42571.428571  ┆ 14    │
│ Data Quality Analyst            ┆ 1956680      ┆ 81528.333333  ┆ 24    │
│ Data Specialist                 ┆ 7761266      ┆ 90247.27907   ┆ 86    │
│ Data Operations Specialist      ┆ 1096840      ┆ 91403.333333  ┆ 12    │
│ Data Management Analyst         ┆ 2035838      ┆ 92538.090909  ┆ 22    │
│ …                               ┆ …            ┆ …             ┆ …     │
│ Big Data Engineer               ┆ 5907600      ┆ 492300.0      ┆ 12    │
│ Applied Machine Learning Scien… ┆ 7767800      ┆ 554842.857143 ┆ 14    │
│ Head of Data Science            ┆ 7015565      ┆ 584630.416667 ┆ 12    │
│ BI Data Analyst                 ┆ 12265000     ┆ 645526.315789 ┆ 19    │
│ Lead Data Scientist             ┆ 8487368      ┆ 771578.909091 ┆ 11    │
└─────────────────────────────────┴──────────────┴───────────────┴───────┘

In [10]:
df.select(
    pl.col('salary_in_usd').mean().round(2).alias('avg_salary'),
    pl.col('salary_in_usd').std().round(2).alias('std_salary'),
    pl.col('salary_in_usd').median().round(2).alias('median_salary'),
    pl.col('salary_in_usd').quantile(0.1).round(2).alias('q1'),
    pl.col('salary_in_usd').quantile(0.25).round(2).alias('q25'),
    pl.col('salary_in_usd').quantile(0.5).round(2).alias('q50'),
    pl.col('salary_in_usd').quantile(0.75).round(2).alias('q75'),
)

shape: (1, 7)
┌────────────┬────────────┬───────────────┬─────────┬──────────┬──────────┬──────────┐
│ avg_salary ┆ std_salary ┆ median_salary ┆ q1      ┆ q25      ┆ q50      ┆ q75      │
│ ---        ┆ ---        ┆ ---           ┆ ---     ┆ ---      ┆ ---      ┆ ---      │
│ f64        ┆ f64        ┆ f64           ┆ f64     ┆ f64      ┆ f64      ┆ f64      │
╞════════════╪════════════╪═══════════════╪═════════╪══════════╪══════════╪══════════╡
│ 149686.78  ┆ 68505.29   ┆ 141300.0      ┆ 71615.0 ┆ 101100.0 ┆ 141300.0 ┆ 185900.0 │
└────────────┴────────────┴───────────────┴─────────┴──────────┴──────────┴──────────┘