In [1]:
import polars as pl
import polars.selectors as cs

import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
df_path = r'/mnt/samsung/Datasets/Student_Placement_Skills_2025/Student_Placement_Skills_2025.csv'

In [3]:
df = pl.read_csv(df_path)

In [4]:
df = pl.read_csv(
    df_path,
    schema_overrides={
        "Student_ID": pl.UInt32,
        "Technical_Skills_Score_100": pl.UInt8,
        "Communication_Skills_Score_100": pl.UInt8,
        "Aptitude_Test_Score_100": pl.UInt8,
        "Internships_Count":    pl.UInt8,
        "Projects_Count":       pl.UInt8,
        "Certifications_Count": pl.UInt8,
        "Salary_Offered_USD": pl.Float32,
        "Gender": pl.Categorical,
        "Degree": pl.Categorical,
        "Placement_Offer": pl.Categorical,
    }
)

In [5]:
df.estimated_size('mb')

0.0240325927734375

In [6]:
df = pl.scan_csv(
    df_path,
    schema_overrides={
        "Student_ID": pl.UInt32,
        "Technical_Skills_Score_100": pl.UInt8,
        "Communication_Skills_Score_100": pl.UInt8,
        "Aptitude_Test_Score_100": pl.UInt8,
        "Internships_Count":    pl.UInt8,
        "Projects_Count":       pl.UInt8,
        "Certifications_Count": pl.UInt8,
        "Salary_Offered_USD": pl.Float32,
        "Gender": pl.Categorical,
        "Degree": pl.Categorical,
        "Placement_Offer": pl.Categorical,
    }
)

In [7]:
print(df.explain())

Csv SCAN [/mnt/samsung/Datasets/Student_Placement_Skills_2025/Student_Placement_Skills_2025.csv]
PROJECT */13 COLUMNS
ESTIMATED ROWS: 663

In [8]:
# Build the lazy query — Polars will push these filters down to the CSV scan
lf = (
    pl.scan_csv(df_path)
    .filter(
        (pl.col("Degree") == "Engineering") &
        (pl.col("Placement_Offer") == "Yes") &
        (pl.col("CGPA") > 3.5)
    )
)

# Confirm predicate pushdown — look for SELECTION inside the CSV_SCAN node
print(lf.explain())

Csv SCAN [/mnt/samsung/Datasets/Student_Placement_Skills_2025/Student_Placement_Skills_2025.csv]
PROJECT */13 COLUMNS
SELECTION: [([([(col("Placement_Offer")) == ("Yes")]) & ([(col("Degree")) == ("Engineering")])]) & ([(col("CGPA")) > (3.5)])]
ESTIMATED ROWS: 663

In [9]:
# Collect and inspect the result
result = lf.collect()
print(f"Rows: {len(result)}")
result

Rows: 22

shape: (22, 13)
┌────────────┬────────┬─────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ Student_ID ┆ Gender ┆ Age ┆ Degree      ┆ … ┆ Communicati ┆ Aptitude_T ┆ Placement_ ┆ Salary_Off │
│ ---        ┆ ---    ┆ --- ┆ ---         ┆   ┆ on_Skills_S ┆ est_Score_ ┆ Offer      ┆ ered_USD   │
│ i64        ┆ str    ┆ i64 ┆ str         ┆   ┆ core_100    ┆ 100        ┆ ---        ┆ ---        │
│            ┆        ┆     ┆             ┆   ┆ ---         ┆ ---        ┆ str        ┆ f64        │
│            ┆        ┆     ┆             ┆   ┆ i64         ┆ i64        ┆            ┆            │
╞════════════╪════════╪═════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 2          ┆ Female ┆ 27  ┆ Engineering ┆ … ┆ 54          ┆ 40         ┆ Yes        ┆ 3518.56    │
│ 111        ┆ Male   ┆ 27  ┆ Engineering ┆ … ┆ 99          ┆ 80         ┆ Yes        ┆ 6350.75    │
│ 115        ┆ Female ┆ 22  ┆ Engineering ┆ … ┆ 60          ┆ 88         ┆ Yes        ┆ 3936.27    │
│ 198        ┆ Male   ┆ 24  ┆ Engineering ┆ … ┆ 97          ┆ 63         ┆ Yes        ┆ 13654.84   │
│ 199        ┆ Female ┆ 22  ┆ Engineering ┆ … ┆ 49          ┆ 65         ┆ Yes        ┆ 10037.77   │
│ …          ┆ …      ┆ …   ┆ …           ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ 493        ┆ Female ┆ 20  ┆ Engineering ┆ … ┆ 66          ┆ 81         ┆ Yes        ┆ 9258.06    │
│ 508        ┆ Female ┆ 23  ┆ Engineering ┆ … ┆ 71          ┆ 52         ┆ Yes        ┆ 16395.53   │
│ 536        ┆ Female ┆ 20  ┆ Engineering ┆ … ┆ 96          ┆ 74         ┆ Yes        ┆ 16141.42   │
│ 542        ┆ Male   ┆ 18  ┆ Engineering ┆ … ┆ 75          ┆ 92         ┆ Yes        ┆ 19639.13   │
│ 585        ┆ Female ┆ 29  ┆ Engineering ┆ … ┆ 81          ┆ 69         ┆ Yes        ┆ 4892.69    │
└────────────┴────────┴─────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [10]:
df.collect()

shape: (600, 13)
┌────────────┬────────┬─────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ Student_ID ┆ Gender ┆ Age ┆ Degree      ┆ … ┆ Communicati ┆ Aptitude_T ┆ Placement_ ┆ Salary_Off │
│ ---        ┆ ---    ┆ --- ┆ ---         ┆   ┆ on_Skills_S ┆ est_Score_ ┆ Offer      ┆ ered_USD   │
│ u32        ┆ cat    ┆ i64 ┆ cat         ┆   ┆ core_100    ┆ 100        ┆ ---        ┆ ---        │
│            ┆        ┆     ┆             ┆   ┆ ---         ┆ ---        ┆ cat        ┆ f32        │
│            ┆        ┆     ┆             ┆   ┆ u8          ┆ u8         ┆            ┆            │
╞════════════╪════════╪═════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 1          ┆ Male   ┆ 19  ┆ Business    ┆ … ┆ 42          ┆ 57         ┆ Yes        ┆ 8047.08007 │
│            ┆        ┆     ┆             ┆   ┆             ┆            ┆            ┆ 8          │
│ 2          ┆ Female ┆ 27  ┆ Engineering ┆ … ┆ 54          ┆ 40         ┆ Yes        ┆ 3518.56005 │
│            ┆        ┆     ┆             ┆   ┆             ┆            ┆            ┆ 9          │
│ 3          ┆ Male   ┆ 26  ┆ Data        ┆ … ┆ 54          ┆ 49         ┆ No         ┆ 11791.75   │
│            ┆        ┆     ┆ Science     ┆   ┆             ┆            ┆            ┆            │
│ 4          ┆ Male   ┆ 18  ┆ Computer    ┆ … ┆ 42          ┆ 72         ┆ Yes        ┆ 13946.2802 │
│            ┆        ┆     ┆ Science     ┆   ┆             ┆            ┆            ┆ 73         │
│ 5          ┆ Male   ┆ 20  ┆ Business    ┆ … ┆ 50          ┆ 53         ┆ No         ┆ 10951.6601 │
│            ┆        ┆     ┆             ┆   ┆             ┆            ┆            ┆ 56         │
│ …          ┆ …      ┆ …   ┆ …           ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ 596        ┆ Female ┆ 22  ┆ Business    ┆ … ┆ 45          ┆ 78         ┆ No         ┆ 14940.1298 │
│            ┆        ┆     ┆             ┆   ┆             ┆            ┆            ┆ 83         │
│ 597        ┆ Male   ┆ 19  ┆ Data        ┆ … ┆ 81          ┆ 63         ┆ Yes        ┆ 8607.62011 │
│            ┆        ┆     ┆ Science     ┆   ┆             ┆            ┆            ┆ 7          │
│ 598        ┆ Male   ┆ 28  ┆ Data        ┆ … ┆ 96          ┆ 82         ┆ No         ┆ 16772.7207 │
│            ┆        ┆     ┆ Science     ┆   ┆             ┆            ┆            ┆ 03         │
│ 599        ┆ Male   ┆ 26  ┆ Engineering ┆ … ┆ 59          ┆ 60         ┆ No         ┆ 4159.31982 │
│            ┆        ┆     ┆             ┆   ┆             ┆            ┆            ┆ 4          │
│ 600        ┆ Female ┆ 19  ┆ Engineering ┆ … ┆ 69          ┆ 90         ┆ No         ┆ 11214.6503 │
│            ┆        ┆     ┆             ┆   ┆             ┆            ┆            ┆ 91         │
└────────────┴────────┴─────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [11]:
df.filter(
    pl.col('Internships_Count') == 0
)

In [15]:
median_salary = df.select(pl.col('Salary_Offered_USD').median()).collect().item()
median_salary

11763.734375

In [16]:
print(f"Median Salary: ${median_salary:.2f}")

Median Salary: $11763.73

In [25]:
result = (
    df.filter(
        (pl.col('Internships_Count') == 0) &
        (pl.col('Certifications_Count') == 0) &
        (pl.col('Placement_Offer') == 'Yes') &
        (pl.col('Salary_Offered_USD') > median_salary)
    )
).collect(engine='streaming')

result

shape: (5, 13)
┌────────────┬────────┬─────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ Student_ID ┆ Gender ┆ Age ┆ Degree      ┆ … ┆ Communicati ┆ Aptitude_T ┆ Placement_ ┆ Salary_Off │
│ ---        ┆ ---    ┆ --- ┆ ---         ┆   ┆ on_Skills_S ┆ est_Score_ ┆ Offer      ┆ ered_USD   │
│ u32        ┆ cat    ┆ i64 ┆ cat         ┆   ┆ core_100    ┆ 100        ┆ ---        ┆ ---        │
│            ┆        ┆     ┆             ┆   ┆ ---         ┆ ---        ┆ cat        ┆ f32        │
│            ┆        ┆     ┆             ┆   ┆ u8          ┆ u8         ┆            ┆            │
╞════════════╪════════╪═════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 244        ┆ Female ┆ 18  ┆ Engineering ┆ … ┆ 65          ┆ 74         ┆ Yes        ┆ 13687.3203 │
│            ┆        ┆     ┆             ┆   ┆             ┆            ┆            ┆ 12         │
│ 451        ┆ Female ┆ 22  ┆ Data        ┆ … ┆ 45          ┆ 56         ┆ Yes        ┆ 16743.4609 │
│            ┆        ┆     ┆ Science     ┆   ┆             ┆            ┆            ┆ 38         │
│ 477        ┆ Male   ┆ 20  ┆ Arts        ┆ … ┆ 46          ┆ 46         ┆ Yes        ┆ 17161.0605 │
│            ┆        ┆     ┆             ┆   ┆             ┆            ┆            ┆ 47         │
│ 483        ┆ Male   ┆ 23  ┆ Arts        ┆ … ┆ 69          ┆ 63         ┆ Yes        ┆ 12323.2998 │
│            ┆        ┆     ┆             ┆   ┆             ┆            ┆            ┆ 05         │
│ 531        ┆ Female ┆ 19  ┆ Arts        ┆ … ┆ 80          ┆ 50         ┆ Yes        ┆ 15166.75   │
└────────────┴────────┴─────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘